apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ilab-test01 
  janus-idp.io/tekton: ilab-test01
  backstage.io/kubernetes-id: ilab-test01
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ilab-test01
resources: 
- application-dev.yaml