apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ilab-test01
  janus-idp.io/tekton: ilab-test01
  backstage.io/kubernetes-id: ilab-test01
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ilab-test01
resources:
- initialize-namespace.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- model-config.yaml
- deployment.yaml
- route.yaml
- service.yaml