---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: ilab-test01
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ilab-test01 
  name: ilab-test01
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi