apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ilab-test01
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ilab-test01 
  name: ilab-test01
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: ilab-test01 
